// This file is automatically generated. Do not edit it directly.
//
// HARDENED: createClient is no longer called at module load. When the env
// vars are missing (paused / deferred backend mode), `supabase` is exported
// as null and any feature that uses it must guard accordingly. This prevents
// `supabaseUrl is required` from crashing the entire SPA at boot when the
// project is running without a configured Supabase backend.
import { createClient, SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL ?? "").trim();
const SUPABASE_PUBLISHABLE_KEY = (
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? ""
).trim();

let _client: SupabaseClient<Database> | null = null;

if (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY) {
  try {
    new URL(SUPABASE_URL);
    _client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: typeof window !== "undefined" ? window.localStorage : undefined,
        persistSession: true,
        autoRefreshToken: true,
      },
    });
  } catch (err) {
    console.error("[supabase] init failed — falling back to disabled mode.", err);
    _client = null;
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
//
// IMPORTANT: this may be `null` if the Supabase env vars are not set.
// All callers should guard with `if (!supabase) { ... }`.
export const supabase = _client as SupabaseClient<Database>;
export const isSupabaseConfigured = _client !== null;
